name: yumwords_cheese
description: YumWords – Cheese
version: 1.0.0+7
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^5.2.1
  scrollable_positioned_list: ^0.3.8
  video_player: ^2.8.6
  shared_preferences: ^2.3.2
  file_picker: ^10.3.2
  path_provider: ^2.1.4
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  # 👉 NEW
  flutter_launcher_icons: ^0.14.3

# 👉 NEW
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/shared/icons/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    # Shared (global)
    - assets/shared/images/ui/
    - assets/shared/flags/
    - assets/shared/maps/
    - assets/shared/icons/

    # France
    # - assets/france/images/ui/
    # - assets/france/images/words/
    # - assets/france/audio/
    # - assets/france/data.json

    # Cheese
    - assets/cheese/images/ui/
    - assets/cheese/images/words/
    - assets/cheese/audio/
    - assets/cheese/data.json
    - assets/cheese/topics.json
    - assets/cheese/topicBlocks.json

    # Other
    - assets/fonts/
    - assets/i18n/

  fonts:
    - family: BebasNeue
      fonts:
        - asset: assets/fonts/Bebas_Neue/BebasNeue-Regular.ttf

    - family: SourceSans3
      fonts:
        - asset: assets/fonts/SourceSans3/SourceSans3-Regular.ttf
          weight: 400
        - asset: assets/fonts/SourceSans3/SourceSans3-Medium.ttf
          weight: 500
        - asset: assets/fonts/SourceSans3/SourceSans3-SemiBold.ttf
          weight: 600

    - family: SourceSerif4
      fonts:
        - asset: assets/fonts/SourceSerif4/SourceSerif4-Regular.ttf

    - family: CharisSIL
      fonts:
        - asset: assets/fonts/CharisSIL/CharisSIL-Regular.ttf
        - asset: assets/fonts/CharisSIL/CharisSIL-Bold.ttf
          weight: 700
        - asset: assets/fonts/CharisSIL/CharisSIL-Italic.ttf
          style: italic

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter/Inter-SemiBold.ttf
          weight: 600

    - family: Sarabun
      fonts:
        - asset: assets/fonts/Sarabun/Sarabun-Regular.ttf
        - asset: assets/fonts/Sarabun/Sarabun-Bold.ttf
          weight: 700
        - asset: assets/fonts/Sarabun/Sarabun-Italic.ttf
          style: italic
        - asset: assets/fonts/Sarabun/Sarabun-BoldItalic.ttf
          weight: 700
          style: italic